#!/bin/sh
if [ $# -le  1 ]; then 
	exit 1
fi

fil=$1
car=$2

echo adding $car to $fil
printf "$car\n" >> $fil

asbuilt=`cat $fil | wc -l`
uniql=`cat $fil | sort | uniq | wc -l`

if [ $asbuilt -ne  $uniql ]; then 
	echo " dupes exist, fix (y/n) ?"
	read fixme
	echo $fixme
	why=y
	if [ $fixme =  $why ]; then
		tf=`mktemp -t mixtape`
		cp $fil  $tf
		cat $tf | sort | uniq > $fil
		rm $tf
	fi
fi


