#!/bin/sh -x

usage(){
	echo "transcode_to mp3 *.wav"
}


if [ $# -le 1 ]; then
	usage
fi

srcformat=$1
destformat=$2

shift 

while  $1
do
	stem=`sed -e "s/\.wav//"`
	echo "sox  '$stem.wav' '$stem.mp3'"
done
echo destformat $destformat
