#!/bin/sh -x
usage(){
	echo "transcode_to '.*Night .*/Cannons .*wav'  'wav' 'mp3'"
	echo # ./Night Drive/Cannons - Night Drive - 03 Kiss Me.wav
}


if [ $# -le 1 ]; then
	usage
	exit
fi

#nerf the IFS global to avoid dumb shell space -> list field splitting
# hope the | isn't in my patterns
IFS='|' 

rpattern=$1
srcformat=$2 # wav
dstformat=$3 # mp3

echo $rpattern
find -s . -regex $rpattern  
echo  ----------------
find -s . -regex $rpattern | sed -e "s/$srcformat/$dstformat/g"

echo ok?
read ok

#find position depentant  so print0 is last
find -s .  -regex $rpattern  -print0 \
	| sed -e "s/$srcformat//g" \
	| xargs -0 -n1 -I% --verbose  \
		sox   --show-progress -V3  \
			%$srcformat \
			--compression 256.01 %$dstformat \
			stats

exit

