#!/bin/sh -x 
bootstrap(){
	#pkg -y
	#pkg install -y git
	#pkg install -y screen

	#bootstrap cantrips
	#git clone https://github.com/agokhale/cantrips
	#cd cantrips
	make install
}

#fix terrible keyboards
sysrc keymap="us.ctrl.kbd"

#- fix ssh host keys
#- fix sshd root login
sed -i .v  's/#PermitRootLogin no/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i .v  's/#GatewayPorts no/GatewayPorts yes/' /etc/ssh/sshd_config
sysrc sshd_enable=yes
service sshd configtest && service sshd restart

#zfs
sysrc zfsd_enable=yes
service zfsd start

#crontabs for locate are .. important to me
## min   hour    daym    month   dayw
#16      8       11       *      *  zpool scrub dozer
#6      */2     *        *      *  /usr/libexec/locate.updatedb
#46      */6     *        *      *  /usr/local/bin/nmap -O 192.168.1.0/24 >> /var/log/nmap/finger-192.168.24.0.print

#smart
pkg install -y  smartmontools
sysrc smartd_enable="YES"
echo 'DEVICESCAN' >> /usr/local/etc/smartd.conf

#add rando swaps to /etc/fstab
swapon -a

#ipmi
pkg install -y ipmitool
pkg install -y openipmi

#dbus - yeah
pkg install -y dbus
sysrc dbus_enable=yes
service dbus start

#avahi,zeroconf,bonjour, 
pkg install -y avahi
sed -I v 's/^hosts.*/hosts: files mdns_minimal [NOTFOUND=return] mdns  dns/' /etc/nsswitch.conf
sysrc avahi_daemon_enable="YES"
service avahi_daemon start
sysrc avahi_dnsconfd_enable="YES"
service avahi_dnsconfd start

#never again: 
echo 'resolvconf=no' > /etc/resolvconf.conf

#fix sudoers
#%wheel ALL=(ALL) NOPASSWD: ALL

pkg install -y gcc-arm-embedded
setenv PATH ${PATH}:/usr/local/gcc-arm-embedded/bin

pkg install -y  chromium

pkg install -y dosunix
pkg install -y stlink


#https://docs.freebsd.org/doc/7.3-RELEASE/usr/share/doc/en/articles/compiz-fusion/nvidia-setup.html

pkg install -y nvidia-ddriver
#echo linux_enable="YES" > /boot/loader.conf
#echo nvidia_load="YES" > /boot/loader.conf
pkg install -y nvidia-xconfig
pkg install -y nvidia-settings

rehash
nvidia-xconfig

sysrc -f /boot/loader.conf linux_load="YES"
sysrc -f /boot/loader.conf nvidia_load="YES"
sysrc -f /boot/loader.conf nvidia-modeset_load="YES"
#needs to kldload nvidia
#needs to kldload nvidia-modeset

sysrc rpcbind_enable="YES"

#nfs server 
sysrc nfs_server_enable="YES"
sysrc nfs_server_flags="-t -u -n 8"
#sysrc nfsv4_server_enable="YES"
#sysrc nfsuserd_enable="YES"

sysrc mountd_enable="YES"
sysrc nfs_client_enable="YES"
sysrc rpc_lockd_enable="YES"
sysrc amd_enable="YES"
sysrc nfsd_enable="YES"


#accelerated xorg gl video 
echo log in user needs video  group
 #pw groupmod video -m ${LOWPRIVUSE}
